SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
IMAGE_PLAYER_HEIGHT = SCREEN_HEIGHT * 1 / 20
IMAGE_PLAYER_WIDTH = SCREEN_WIDTH * 3 / 100  # 30
WALL_WIDTH = SCREEN_WIDTH * 1 / 20
PLATFORM_HEIGHT = SCREEN_HEIGHT * 1 / 50
SCREEN = (SCREEN_WIDTH, SCREEN_HEIGHT)
MAX_Y_PLAYER_VELOCITY = 55
