SCREEN_WIDTH = 900
SCREEN_HEIGHT = 900
IMAGE_PLAYER_HEIGHT = SCREEN_HEIGHT * 1 / 20
IMAGE_PLAYER_WIDTH = SCREEN_WIDTH * 3 / 100  # 30
WALL_WIDTH = SCREEN_WIDTH * 1 / 20
PLATFORM_HEIGHT = SCREEN_HEIGHT * 1 / 50
SCREEN = (SCREEN_WIDTH, SCREEN_HEIGHT)
